#based on vit_b16_c4_ep10_batch1_ctxv1.yaml

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 1
  TEST:
    BATCH_SIZE: 80
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 10
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  NAME: "CoCoOpEnsemblingLAIONized"
  COCOOP_ENSEMBLING_LAIONIZED:
    RANDOM_CTX_INIT: True
    TRAIN_SEPARATELY: True
    PREC: "fp16"
    ONETOKEN: True
    NOPERIOD: True
    LAION_NUM_POSITIVES: 1
    LAION_LAMBDA: 1.0
    GRAMLEN: 5
